add(translations): Chinese Simplified
pop-os/repoman pull request #101
Opened 2022-07-14 10:52 UTC by RX-CaO

add Chinese Simplified support.

2022-07-14 15:07 UTC, jacobgkau commented
This is currently not showing up in a user account set to Chinese.

Looking at the .po file, the language code is set to `zh-CN` (with a hyphen); the working Portuguese (Brazil) translation has its language code set to `pt_BR` (with an underscore.) That might be the issue.

2022-07-14 19:00 UTC, n3m0-22 requested changes
To fix the build errors and allow this to work the following need to be changed:

- rename the file`zh-CN.po` to `zh_CN.po`
- rename the directory `po/zh-CN` to `po/zh_CN`

Then run the following commands from the `popos-repoman` directory :

-  `xgettext -L Python -d repoman -p po/ -o repoman.pot repoman/*`
-  `msgmerge po/zh_CN.po po/repoman.pot -U`
-  `msgfmt -o po/zh_CN/repoman.mo po/zh_CN.po`
-  `msginit -i po/repoman.pot -o po/zh_CN.po -l zh_CN`
-  `msgfmt -o po/zh_CN/repoman.mo po/zh_CN.po`

2022-07-15 13:59 UTC, n3m0-22 approved these changes
This is working now. The translation looks good. Thank you for your contribution.

2022-07-19 00:04 UTC, 13r0ck approved these changes

2022-07-19 00:06 UTC, merged