Apt delete button
pop-os/repoman pull request #44
Opened 2020-01-30 21:23 UTC by isantop

Moves the remove button for Apt sources from the edit dialog into the main window (in the action bar).

This brings the UI more in line with the Flatpak pane, and makes removing multiple sources a bit easier. 

Fixes #40

2020-02-03 17:46 UTC, brs17 approved these changes

2020-02-03 18:04 UTC, brs17 commented
When selecting the `Delete` button without having a source selected, once I close out of repoman I get the following error in journald:

```
Feb 03 10:13:51 pop-os io.elementary.appcenter.desktop[1774]: Traceback (most recent call last):
Feb 03 10:13:51 pop-os io.elementary.appcenter.desktop[1774]:   File "/usr/lib/python3/dist-packages/repoman/list.py", line 127, in on_delete_button_clicked
Feb 03 10:13:51 pop-os io.elementary.appcenter.desktop[1774]:     tree_iter = model.get_iter(pathlist[0])
Feb 03 10:13:51 pop-os io.elementary.appcenter.desktop[1774]: IndexError: list index out of range
```

Shouldn't this be dealt with instead of throwing an IndexError?

2020-02-03 18:05 UTC, brs17 requested changes
^^

2020-02-04 18:17 UTC, isantop commented
@brs17 I think the best way to deal with this would be to set those buttons insensitive and only allow clicking on them when a row is selected. 

Every button in a list in the application (including the Info and Delete buttons on the flatpak page) also show this error, including in master. Since clicking the button without a row selected doesn't result in a broken/dangerous action taking place and we generally expect that repoman will be run from within Pop Shop instead of via the command line, I think it would be best to address this issue in a separate PR (since all of the buttons have the same issue, and are caused by the same problem, and will be fixed with the same code.

2020-02-04 21:03 UTC, brs17 approved these changes

2020-02-04 22:14 UTC, jackpot51 approved these changes

2020-02-04 22:44 UTC, merged