Reset checkmarks
pop-os/repoman pull request #71
Opened 2020-07-16 15:20 UTC by isantop

Resets the checkboxes on the Updates page when changes are made to the checks on the Settings page. This is required because the settings pages enable or disable components (`main`, `universe`, etc.) but the Updates tab adds or removes lines. If all components are disabled, the Updates page loses sync with the actual state of the sources.list file.

With this change, if all items are unchecked in the settings page, the checkboxes in the updates page will end up disabled too, matching the state of the sources.list file. When components are enabled again, these remain unchecked (which matches the behavior in the Ubuntu `software-properties-gtk` package.

2020-07-16 21:18 UTC, jackpot51 submitted a review, later dismissed

2020-07-16 21:57 UTC, leviport requested changes
Checkboxes in the "Updates" tab now match sources.list much better. However in the "Settings" tab, under "Developer Options (Advanced)", the "Include source code" box now seems to have the same sort of issue. 

If I remove all four of the official sources, all of the `deb-src` lines also get removed. The "Include Source Code" box does not get unchecked as I would expect.

I'm also noticing that if "Include source code" is checked, any sources in "Updates" that are unchecked and re-checked don't have the deb-src line added when the deb line is added. To get the deb-src lines back, I have to un-check and re-check the "Include source code" box. I have not compared this behavior to software-properties-gtk.

2020-07-28 21:14 UTC, isantop commented
@leviport I've re-worked this a bit to help minimize slowdowns when disabling all of the distro components while addressing your feedback. Current behavior:

1. When a component is unchecked with other components enabled, the UI should respond instantly. 
2. When the last enabled component is unchecked, all of the child repo checks should be unchecked automatically and disabled (on both the updates page and the settings page). The UI will momentarily freeze, but this should be brief. I don't think we can work around this.
3. Re-checking a component will re-enable all of the child repos in the unchecked state, allowing the user to re-enable them. There should be no significant freezes to re-enable any component.

2020-07-28 23:15 UTC, leviport commented
The latest changes are definitely an improvement! I'm also not seeing the hesitation you describe when unchecking the final enabled component, so that's good.

I am noticing another checkbox inconsistency though. If I uncheck Universe and Multiverse, I see them being removed from `/etc/apt/sources.list` as expected. If I re-enable Multiverse, I also see Universe get re-added in `/etc/apt/sources.list`, but the checkbox is not updated in Repoman. In software-properties-gtk, Universe is also re-added, but the checkbox is also updated. You can see this behavior in this video: [Peek 2020-07-28 17-05.zip](https://github.com/pop-os/repoman/files/4991612/Peek.2020-07-28.17-05.zip)

2020-07-29 18:40 UTC, isantop commented
@leviport Should be fixed as of 3bb884f

2020-07-29 20:08 UTC, leviport approved these changes
The universe/multiverse thing is now resolved. 

I also tested in 18.04 and it looks good there as well.

2020-07-31 16:08 UTC, jackpot51 approved these changes

2020-08-03 15:10 UTC, merged