fix(repo): use repolib get_all_sources() method to fetch sources
pop-os/repoman pull request #83
Opened 2020-10-26 17:52 UTC by isantop

This is better than doing it manually because we weren't catching errors, leading to repoman crashing on startup if there was an invalid source. Now it will skip the invalid sources instead of crashing

This will help ensure that even if there are invalid sources on the system Repoman will launch without the invalid sources (while the rest of the sources will be available).

It also sets us up for the better error handling in Repolib coming shortly.

2020-10-26 20:05 UTC, ids1024 submitted a review, later dismissed

2020-10-27 14:59 UTC, jacobgkau requested changes
I'm not able to edit valid sources that were editable before this change. I get tracebacks like this every time I click the Edit button on the Extra Sources page, where the "KeyError" line shows the source I'm trying to edit:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 166, in on_edit_button_clicked
    self.do_edit(repo_name)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 180, in do_edit
    source = self.sources[repo_name]
KeyError: 'maarten-baert-ubuntu-simplescreenrecorder-focal.list'
```

2020-10-27 16:37 UTC, jacobgkau commented
That fixed the editing issue, I am now able to add and modify sources; however, I am not able to remove sources. I don't see any terminal output to indicate the issue. I am prompted for authentication as expected, but then the source is not removed from the list and its file is still present in `sources.list.d`.

2020-10-27 17:54 UTC, isantop commented
@jacobgkau I see the problem, and should be fixed as of c216d30

2020-10-27 18:27 UTC, jacobgkau approved these changes
Everything looks good now.

2020-10-27 19:03 UTC, ids1024 approved these changes

2020-10-27 19:05 UTC, merged